### ISSUE TITLE
Use a closure to also lock on value

### ISSUE THREAD

**Issue by bryaan** [wherrera10/ThreadSafeDicts.jl#11]
Would it be possible to do something like:

```
get(dict, key) do
   # within lock
end
```

So we can reuse the lock and simplify logic while updating the value struct?

**Comment by wherrera10** [comment]
I would try:

lock(dict.dlock) do
       …. Body ….
end

Which might work when dict is a ThreadSafeDict, as this would get the
thread the lock during do block execution.  You would need to verify that
calls to the dict. Function work properly when called within the do block.



Are you suggesting an additional feature for the package?

**Comment by wherrera10** [comment]
I got around to looking at your question further. If you are using the
ThreadSafeDict within a lock do block:

eg.

lock(dict.dlock) do
    dict.d[10] = 20
    println("\n", dict.d)
end

... you cannot call the locked functions as the lock's being locked by the
same thread does not seem to be known to Julia. You would need to use the
underlying `d` Dict member within the loop to avoid deadlock.

In general, if you lock the dict manually in this way, you need to do as
little as possible within your exclusive code block, to avoid pausing other
threads for too long.

**Comment by wherrera10** [comment]
Provisionally added here: https://github.com/wherrera10/ThreadSafeDicts.jl/commit/161adf9a0667c3be3a425250486ef09f4b8a8b28

**Comment by wherrera10** [comment]
Tested. Will release this soon.
