### ISSUE TITLE
key not found would block

### ISSUE THREAD

**Issue by xgdgsc** [wherrera10/ThreadSafeDicts.jl#13]
When a key isn' t found in dict. It become an uninterruptable program. https://discourse.julialang.org/t/poor-performance-of-lock-l-do-closures-caused-by-poor-performance-of-capturing-closures/42067/13 using `@lock` might fix this.

**Comment by wherrera10** [comment]
See fix at https://github.com/wherrera10/ThreadSafeDicts.jl/commit/68080d32b61fd9f5c46cad02eef4367843d8e1b1
