### ISSUE TITLE
Type stability of the underlying dict

### ISSUE THREAD

**Issue by zengmao** [wherrera10/ThreadSafeDicts.jl#14]
The struct definition
```
struct ThreadSafeDict{K, V} <: AbstractDict{K, V}
    dlock::Threads.SpinLock
    d::Dict
    ThreadSafeDict{K, V}() where V where K = new(Threads.SpinLock(), Dict{K, V}())
    ThreadSafeDict{K, V}(itr) where V where K = new(Threads.SpinLock(), Dict{K, V}(itr))
end
```
contains `d::Dict` which has an abstract type. This can cause runtime dispatch and affect performance. It should be easy to change it to `d::Dict{K, V}`, which also makes better use of the type information already supplied, unless I missed something.

**Comment by wherrera10** [comment]
Hm, I had thought that the Dict would specialize as needed, but can test
that change.

**Comment by zengmao** [comment]
Unfortunately, only functions specialize, and struct fields do not specialize. For example, see Julia manual's performance tip, "Avoid fields with abstract type":
https://docs.julialang.org/en/v1/manual/performance-tips/#Avoid-fields-with-abstract-type
and "Avoid fields with abstract containers":
https://docs.julialang.org/en/v1/manual/performance-tips/#Avoid-fields-with-abstract-containers

**Comment by wherrera10** [comment]
Merged, will push to registry later if holds up.  Thanks!  :)
